#!/usr/bin/env python
__author__ = "Prashant Shivarm Bhat"
__email__ = "PrashantShivaram@outlook.com"

# Do NOT edit this file !

# Meta data concerning each feature in an individual
N_NAME = 'node_name'
F_IMP = 'feature_importance'
A_GRAPH = 'ancestor_graph'

# Unary Transformers
SQR = 'square'
LOG = 'log'
SQRT = 'square_root'
MATH_OPS = [LOG, SQR, SQRT]

# preprocessors
KBD = 'k_bins_discretizer'
MMS = 'min_max_scaler'
MAS = 'max_abs_scaler'
PRE_PROCESSORS = [KBD, MMS, MAS]

# General constants frequently used in the code
INX = 'index'
IND = 'individual'
